# Form implementation generated from reading ui file 'between_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_between_window(object):
    def setupUi(self, between_window):
        between_window.setObjectName("between_window")
        between_window.resize(717, 645)
        self.centralwidget = QtWidgets.QWidget(between_window)
        self.centralwidget.setObjectName("centralwidget")
        self.patientName = QtWidgets.QLabel(self.centralwidget)
        self.patientName.setGeometry(QtCore.QRect(100, 20, 91, 31))
        self.patientName.setObjectName("patientName")
        self.patientAge = QtWidgets.QLabel(self.centralwidget)
        self.patientAge.setGeometry(QtCore.QRect(100, 50, 21, 21))
        self.patientAge.setObjectName("patientAge")
        self.patientAge_Years = QtWidgets.QLabel(self.centralwidget)
        self.patientAge_Years.setGeometry(QtCore.QRect(120, 50, 51, 21))
        self.patientAge_Years.setObjectName("patientAge_Years")
        self.pastmedicalhistory_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.pastmedicalhistory_BTN.setGeometry(QtCore.QRect(410, 110, 181, 41))
        self.pastmedicalhistory_BTN.setObjectName("pastmedicalhistory_BTN")
        self.medication_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.medication_BTN.setGeometry(QtCore.QRect(410, 150, 181, 41))
        self.medication_BTN.setObjectName("medication_BTN")
        self.pathology_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.pathology_BTN.setGeometry(QtCore.QRect(410, 190, 181, 41))
        self.pathology_BTN.setObjectName("pathology_BTN")
        self.prescribe_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.prescribe_BTN.setGeometry(QtCore.QRect(470, 480, 113, 32))
        self.prescribe_BTN.setObjectName("prescribe_BTN")
        self.examination_label = QtWidgets.QLabel(self.centralwidget)
        self.examination_label.setGeometry(QtCore.QRect(100, 240, 91, 28))
        font = QtGui.QFont()
        font.setBold(True)
        self.examination_label.setFont(font)
        self.examination_label.setObjectName("examination_label")
        self.conclusion_label = QtWidgets.QLabel(self.centralwidget)
        self.conclusion_label.setGeometry(QtCore.QRect(100, 380, 81, 28))
        font = QtGui.QFont()
        font.setBold(True)
        self.conclusion_label.setFont(font)
        self.conclusion_label.setObjectName("conclusion_label")
        self.examination_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.examination_text.setGeometry(QtCore.QRect(100, 270, 256, 111))
        self.examination_text.setObjectName("examination_text")
        self.history_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.history_text.setGeometry(QtCore.QRect(100, 110, 256, 131))
        self.history_text.setObjectName("history_text")
        self.history_label = QtWidgets.QLabel(self.centralwidget)
        self.history_label.setGeometry(QtCore.QRect(100, 80, 61, 28))
        font = QtGui.QFont()
        font.setBold(True)
        self.history_label.setFont(font)
        self.history_label.setObjectName("history_label")
        self.conclusion_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.conclusion_text.setGeometry(QtCore.QRect(100, 410, 256, 101))
        self.conclusion_text.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextBrowserInteraction|QtCore.Qt.TextInteractionFlag.TextEditable|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.conclusion_text.setObjectName("conclusion_text")
        self.bloodpressure_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.bloodpressure_BTN.setGeometry(QtCore.QRect(410, 230, 181, 41))
        self.bloodpressure_BTN.setObjectName("bloodpressure_BTN")
        between_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(between_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        between_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(between_window)
        self.statusbar.setObjectName("statusbar")
        between_window.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(between_window)
        QtCore.QMetaObject.connectSlotsByName(between_window)

    def retranslateUi(self, between_window):
        _translate = QtCore.QCoreApplication.translate
        between_window.setWindowTitle(_translate("between_window", "MainWindow"))
        self.patientName.setText(_translate("between_window", "Mr John Smith"))
        self.patientAge.setText(_translate("between_window", "42"))
        self.patientAge_Years.setText(_translate("between_window", "Years"))
        self.pastmedicalhistory_BTN.setText(_translate("between_window", "Past Medical History"))
        self.medication_BTN.setText(_translate("between_window", "Medication History"))
        self.pathology_BTN.setText(_translate("between_window", "Pathology"))
        self.prescribe_BTN.setText(_translate("between_window", "Prescribe"))
        self.examination_label.setText(_translate("between_window", "Examination"))
        self.conclusion_label.setText(_translate("between_window", "Conclusion"))
        self.examination_text.setHtml(_translate("between_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Clear Chest</p></body></html>"))
        self.history_text.setHtml(_translate("between_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">52 year old male</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">presenting with 4 week history of cough</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.history_label.setText(_translate("between_window", "History"))
        self.conclusion_text.setHtml(_translate("between_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Likely LRTI - Plan for abx</p></body></html>"))
        self.bloodpressure_BTN.setText(_translate("between_window", "Blood Pressure"))
        self.menuFile.setTitle(_translate("between_window", "File"))
