# Form implementation generated from reading ui file 'bloodpressure.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_bp_dlg(object):
    def setupUi(self, bp_dlg):
        bp_dlg.setObjectName("bp_dlg")
        bp_dlg.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(bp_dlg)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.bloodpressure_table = QtWidgets.QTableView(bp_dlg)
        self.bloodpressure_table.setGeometry(QtCore.QRect(10, 40, 381, 191))
        self.bloodpressure_table.setObjectName("bloodpressure_table")
        self.pastmedicalhistory_label = QtWidgets.QLabel(bp_dlg)
        self.pastmedicalhistory_label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.pastmedicalhistory_label.setObjectName("pastmedicalhistory_label")

        self.retranslateUi(bp_dlg)
        self.buttonBox.accepted.connect(bp_dlg.accept) # type: ignore
        self.buttonBox.rejected.connect(bp_dlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(bp_dlg)

    def retranslateUi(self, bp_dlg):
        _translate = QtCore.QCoreApplication.translate
        bp_dlg.setWindowTitle(_translate("bp_dlg", "Dialog"))
        self.pastmedicalhistory_label.setText(_translate("bp_dlg", "Blood Pressure"))
