# Form implementation generated from reading ui file 'cases.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1225, 996)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.case1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.case1_btn.setGeometry(QtCore.QRect(430, 340, 321, 91))
        self.case1_btn.setObjectName("case1_btn")
        self.case2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.case2_btn.setGeometry(QtCore.QRect(430, 700, 321, 91))
        self.case2_btn.setObjectName("case2_btn")
        self.case3_btn = QtWidgets.QPushButton(self.centralwidget)
        self.case3_btn.setGeometry(QtCore.QRect(430, 430, 321, 91))
        self.case3_btn.setObjectName("case3_btn")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(1100, 910, 113, 32))
        self.resetButton.setObjectName("resetButton")
        self.case4_btn = QtWidgets.QPushButton(self.centralwidget)
        self.case4_btn.setGeometry(QtCore.QRect(430, 790, 321, 91))
        self.case4_btn.setObjectName("case4_btn")
        self.case5_btn = QtWidgets.QPushButton(self.centralwidget)
        self.case5_btn.setGeometry(QtCore.QRect(430, 520, 321, 91))
        self.case5_btn.setObjectName("case5_btn")
        self.case6_btn = QtWidgets.QPushButton(self.centralwidget)
        self.case6_btn.setGeometry(QtCore.QRect(430, 610, 321, 91))
        self.case6_btn.setObjectName("case6_btn")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(180, 0, 791, 331))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1225, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.case1_btn.setText(_translate("MainWindow", "Case 1"))
        self.case2_btn.setText(_translate("MainWindow", "Case 2"))
        self.case3_btn.setText(_translate("MainWindow", "Case 3"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.case4_btn.setText(_translate("MainWindow", "Case 4"))
        self.case5_btn.setText(_translate("MainWindow", "Case 5"))
        self.case6_btn.setText(_translate("MainWindow", "Case 6"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Thank you for taking part in this test. 6 cases are presented below. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">For each case:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">1) </span><span style=\" font-size:18pt; font-weight:700;\">Click</span><span style=\" font-size:18pt;\"> on the first case below. A new window will open. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">2) Read the </span><span style=\" font-size:18pt; font-weight:700;\">history, examination and conclusion. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">3) You can click on any buttons you see on the new window. Some cases will not have any additional buttons and all information will be displayed in the same window. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">4) Make a decision on what to prescribe, and then </span><span style=\" font-size:18pt; font-weight:700;\">click the prescribe button.</span><span style=\" font-size:18pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">5) Enter your prescription and click ok. This will save the case and you can </span><span style=\" font-size:18pt; font-weight:700;\">move on to the next one.</span><span style=\" font-size:18pt;\"><br /><br /></span><span style=\" font-size:18pt; font-weight:700;\">You can assume the patient is well enough to be sent home with a prescription and appropriate follow up is arranged. This is not a test of knowledge or skill, so don\'t be too concerned about getting doses etc 100% correct. </span></p></body></html>"))
