# Form implementation generated from reading ui file 'pmh.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pmh_dlg(object):
    def setupUi(self, pmh_dlg):
        pmh_dlg.setObjectName("pmh_dlg")
        pmh_dlg.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(pmh_dlg)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.past_medical_history_table = QtWidgets.QTableView(pmh_dlg)
        self.past_medical_history_table.setGeometry(QtCore.QRect(10, 40, 381, 191))
        self.past_medical_history_table.setObjectName("past_medical_history_table")
        self.pastmedicalhistory_label = QtWidgets.QLabel(pmh_dlg)
        self.pastmedicalhistory_label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.pastmedicalhistory_label.setObjectName("pastmedicalhistory_label")

        self.retranslateUi(pmh_dlg)
        self.buttonBox.accepted.connect(pmh_dlg.accept) # type: ignore
        self.buttonBox.rejected.connect(pmh_dlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(pmh_dlg)

    def retranslateUi(self, pmh_dlg):
        _translate = QtCore.QCoreApplication.translate
        pmh_dlg.setWindowTitle(_translate("pmh_dlg", "Dialog"))
        self.pastmedicalhistory_label.setText(_translate("pmh_dlg", "Past Medical History"))
