# Form implementation generated from reading ui file 'within_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_within_window(object):
    def setupUi(self, within_window):
        within_window.setObjectName("within_window")
        within_window.resize(918, 885)
        self.centralwidget = QtWidgets.QWidget(within_window)
        self.centralwidget.setObjectName("centralwidget")
        self.patientName = QtWidgets.QLabel(self.centralwidget)
        self.patientName.setGeometry(QtCore.QRect(100, 10, 181, 31))
        self.patientName.setObjectName("patientName")
        self.patientAge = QtWidgets.QLabel(self.centralwidget)
        self.patientAge.setGeometry(QtCore.QRect(100, 40, 21, 21))
        self.patientAge.setObjectName("patientAge")
        self.patientAge_Years = QtWidgets.QLabel(self.centralwidget)
        self.patientAge_Years.setGeometry(QtCore.QRect(120, 40, 51, 21))
        self.patientAge_Years.setObjectName("patientAge_Years")
        self.prescribe_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.prescribe_BTN.setGeometry(QtCore.QRect(740, 750, 113, 32))
        self.prescribe_BTN.setObjectName("prescribe_BTN")
        self.examination_label = QtWidgets.QLabel(self.centralwidget)
        self.examination_label.setGeometry(QtCore.QRect(100, 240, 81, 28))
        font = QtGui.QFont()
        font.setBold(True)
        self.examination_label.setFont(font)
        self.examination_label.setObjectName("examination_label")
        self.conclusion_label = QtWidgets.QLabel(self.centralwidget)
        self.conclusion_label.setGeometry(QtCore.QRect(100, 380, 81, 28))
        font = QtGui.QFont()
        font.setBold(True)
        self.conclusion_label.setFont(font)
        self.conclusion_label.setObjectName("conclusion_label")
        self.examination_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.examination_text.setGeometry(QtCore.QRect(100, 270, 256, 111))
        self.examination_text.setObjectName("examination_text")
        self.history_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.history_text.setGeometry(QtCore.QRect(100, 110, 256, 131))
        self.history_text.setObjectName("history_text")
        self.history_label = QtWidgets.QLabel(self.centralwidget)
        self.history_label.setGeometry(QtCore.QRect(100, 78, 51, 28))
        font = QtGui.QFont()
        font.setBold(True)
        self.history_label.setFont(font)
        self.history_label.setObjectName("history_label")
        self.conclusion_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.conclusion_text.setGeometry(QtCore.QRect(100, 410, 256, 101))
        self.conclusion_text.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextBrowserInteraction|QtCore.Qt.TextInteractionFlag.TextEditable|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.conclusion_text.setObjectName("conclusion_text")
        self.pastmedicalhistory_label = QtWidgets.QLabel(self.centralwidget)
        self.pastmedicalhistory_label.setGeometry(QtCore.QRect(370, 90, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.pastmedicalhistory_label.setFont(font)
        self.pastmedicalhistory_label.setObjectName("pastmedicalhistory_label")
        self.past_medical_history_table = QtWidgets.QTableView(self.centralwidget)
        self.past_medical_history_table.setGeometry(QtCore.QRect(370, 110, 481, 131))
        self.past_medical_history_table.setObjectName("past_medical_history_table")
        self.medication_table = QtWidgets.QTableView(self.centralwidget)
        self.medication_table.setGeometry(QtCore.QRect(370, 270, 481, 131))
        self.medication_table.setObjectName("medication_table")
        self.medication_label = QtWidgets.QLabel(self.centralwidget)
        self.medication_label.setGeometry(QtCore.QRect(370, 250, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.medication_label.setFont(font)
        self.medication_label.setObjectName("medication_label")
        self.pathology_label = QtWidgets.QLabel(self.centralwidget)
        self.pathology_label.setGeometry(QtCore.QRect(370, 440, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.pathology_label.setFont(font)
        self.pathology_label.setObjectName("pathology_label")
        self.pathology_table = QtWidgets.QTableView(self.centralwidget)
        self.pathology_table.setGeometry(QtCore.QRect(370, 460, 481, 121))
        self.pathology_table.setSortingEnabled(False)
        self.pathology_table.setObjectName("pathology_table")
        self.bloodpressure_table = QtWidgets.QTableView(self.centralwidget)
        self.bloodpressure_table.setGeometry(QtCore.QRect(370, 610, 481, 131))
        self.bloodpressure_table.setSortingEnabled(False)
        self.bloodpressure_table.setObjectName("bloodpressure_table")
        self.bloodpressure_label = QtWidgets.QLabel(self.centralwidget)
        self.bloodpressure_label.setGeometry(QtCore.QRect(370, 590, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.bloodpressure_label.setFont(font)
        self.bloodpressure_label.setObjectName("bloodpressure_label")
        self.allergy_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.allergy_textBrowser.setGeometry(QtCore.QRect(370, 400, 481, 31))
        self.allergy_textBrowser.setObjectName("allergy_textBrowser")
        within_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(within_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        within_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(within_window)
        self.statusbar.setObjectName("statusbar")
        within_window.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(within_window)
        QtCore.QMetaObject.connectSlotsByName(within_window)

    def retranslateUi(self, within_window):
        _translate = QtCore.QCoreApplication.translate
        within_window.setWindowTitle(_translate("within_window", "MainWindow"))
        self.patientName.setText(_translate("within_window", "Mr John Smith"))
        self.patientAge.setText(_translate("within_window", "42"))
        self.patientAge_Years.setText(_translate("within_window", "Years"))
        self.prescribe_BTN.setText(_translate("within_window", "Prescribe"))
        self.examination_label.setText(_translate("within_window", "Examination"))
        self.conclusion_label.setText(_translate("within_window", "Conclusion"))
        self.examination_text.setHtml(_translate("within_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Clear Chest</p></body></html>"))
        self.history_text.setHtml(_translate("within_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">52 year old male</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">presenting with 4 week history of cough</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.history_label.setText(_translate("within_window", "History"))
        self.conclusion_text.setHtml(_translate("within_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Likely LRTI - Plan for abx</p></body></html>"))
        self.pastmedicalhistory_label.setText(_translate("within_window", "Past Medical History"))
        self.medication_label.setText(_translate("within_window", "Medication"))
        self.pathology_label.setText(_translate("within_window", "Pathology"))
        self.bloodpressure_label.setText(_translate("within_window", "Blood Pressure"))
        self.allergy_textBrowser.setHtml(_translate("within_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">NO KNOWN DRUG ALLERGIES</span></p></body></html>"))
        self.menuFile.setTitle(_translate("within_window", "File"))
